// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, http, path, routes, server;

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  app = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.engine('html', require('ejs').renderFile);
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.configure('development', function() {
    app.use(express.errorHandler());
  });

  app.get('/', function(req, res) {
    res.render('index.html');
  });

  server = http.createServer(app).listen(app.get('port'), function() {
    console.log('express listening on port ' + app.get('port'));
  });

}).call(this);
