// Generated by CoffeeScript 1.4.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {});

  app.listen(3000);

  console.log('listening on port 3000');

}).call(this);
